wip: dump stacktraces for any processes holding files

diff --git a/.github/actions/save-coverage-data/action.yml b/.github/actions/save-coverage-data/action.yml
--- a/.github/actions/save-coverage-data/action.yml
+++ b/.github/actions/save-coverage-data/action.yml
@@ -10,7 +10,14 @@ runs:
 
     - name: List pids for profraw
       shell: bash -euxo pipefail {0}
-      run: find /tmp/coverage -type f | xargs -I{} fuser {}
+      run: |
+        # lsof returns 1 if no one uses the file; xargs then returns 123
+        pids=$(find /tmp/coverage -type f | xargs -I{} lsof -t {} || true)
+        for pid in "${pids[@]}"; do
+          echo "$pid: $(cat /proc/$pid/cmdline) ----"
+          gdb -p $pid --batch -ex "thread apply all bt" || echo "gdb failed with $?"
+          echo
+        done
 
     - name: Merge coverage data
       shell: bash -euxo pipefail {0}
