CI(build-tools): use docker to build image

diff --git a/.github/workflows/build-build-tools-image.yml b/.github/workflows/build-build-tools-image.yml
--- a/.github/workflows/build-build-tools-image.yml
+++ b/.github/workflows/build-build-tools-image.yml
@@ -3,12 +3,12 @@ name: Build build-tools image
 on:
   workflow_call:
     outputs:
-      image:
-        description: "build-tools docker image (with digest)"
-        value: ${{ jobs.check-image.outputs.full-image || jobs.manifest.outputs.full-image }}
       tag:
-        description: "build-tools docker image tag"
+        description: "build-tools image tag"
         value: ${{ jobs.check-image.outputs.tag }}
+      image:
+        description: "build-tools image"
+        value: neondatabase/build-tools:${{ jobs.check-image.outputs.tag }}
 
 defaults:
   run:
@@ -21,8 +21,8 @@ jobs:
   check-image:
     runs-on: ubuntu-latest
     outputs:
-      full-image: ${{ steps.check-image.outputs.image }}
       tag: ${{ steps.get-build-tools-tag.outputs.image-tag }}
+      build_required: ${{ steps.check-image.outputs.build_required }}
 
     steps:
       - name: Get build-tools image tag for current commit
@@ -48,69 +48,63 @@ jobs:
         id: check-image
         env:
           IMAGE_TAG: ${{ steps.get-build-tools-tag.outputs.image-tag }}
-          # We run CI pipeline on x86_64 arch only
-          ARCH: amd64
         run: |
-          digest=$(docker manifest inspect neondatabase/build-tools:${IMAGE_TAG} | jq ".manifests[] | select(.platform.architecture == '${ARCH}') | .digest" || true)
-          if [[ -n "${digest}" ]]; then
-            image="neondatabase/build-tools:${IMAGE_TAG}@${digest}"
+          if [[ -z "$(docker manifest inspect neondatabase/build-tools:${IMAGE_TAG} || true)" ]]; then
+            build_required=true
           else
-            image=""
+            build_required=false
           fi
 
-          echo "image=${image}" | tee -a $GITHUB_OUTPUT
+          echo "build_required=${build_required}" | tee -a $GITHUB_OUTPUT
 
-  kaniko:
+  # This job uses older version of GitHub Actions because it's run on gen2 runners, which don't support node 20 (for newer versions)
+  build-image:
     needs: [ check-image ]
-    if: needs.check-image.outputs.full-image == ''
+    if: needs.check-image.outputs.build_required == 'true'
 
     strategy:
       matrix:
         arch: [ x64, arm64 ]
 
     runs-on: ${{ fromJson(format('["self-hosted", "dev", "{0}"]', matrix.arch)) }}
-    container: gcr.io/kaniko-project/executor:v1.7.0-debug
-
-    # kaniko image doesn't have bash
-    defaults:
-      run:
-        shell: sh -euo pipefail {0}
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v1
+      - uses: actions/checkout@v3
 
-      - name: Configure Docker Hub login
+      # Use custom DOCKER_CONFIG directory to avoid conflicts with default settings
+      # The default value is ~/.docker
+      - name: Set custom docker config directory
         run: |
-          DOCKERHUB_AUTH=$(echo -n "${{ secrets.NEON_DOCKERHUB_USERNAME }}:${{ secrets.NEON_DOCKERHUB_PASSWORD }}" | base64)
-          echo "::add-mask::${DOCKERHUB_AUTH}"
+          mkdir -p /tmp/.docker-custom
+          echo DOCKER_CONFIG=/tmp/.docker-custom >> $GITHUB_ENV
 
-          cat <<-EOF > /kaniko/.docker/config.json
-            {
-              "auths": {
-                "https://index.docker.io/v1/": {
-                  "auth": "${DOCKERHUB_AUTH}"
-                }
-              }
-            }
-          EOF
+      - uses: docker/setup-buildx-action@v2
 
-      - name: Kaniko build
+      - uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
+          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}
+
+      - uses: docker/build-push-action@v4
+        with:
+          context: .
+          platforms: ${{ matrix.arch == 'x64' && 'linux/amd64' || 'linux/arm64' }}
+          provenance: false
+          push: true
+          pull: true
+          file: Dockerfile.build-tools
+          cache-from: type=registry,ref=neondatabase/build-tools:cache-${{ matrix.arch }}
+          cache-to: type=registry,ref=neondatabase/build-tools:cache-${{ matrix.arch }},mode=max
+          tags: neondatabase/build-tools:${{ needs.check-image.outputs.tag }}-${{ matrix.arch }}
+
+      - name: Remove custom docker config directory
+        if: always()
         run: |
-          /kaniko/executor \
-            --reproducible \
-            --snapshotMode=redo \
-            --skip-unused-stages \
-            --dockerfile Dockerfile.build-tools \
-            --cache=true \
-            --cache-repo neondatabase/cache \
-            --destination neondatabase/build-tools:${{ needs.check-image.outputs.tag }}-${{ matrix.arch }}
+          rm -rf /tmp/.docker-custom
 
-  manifest:
-    needs: [ check-image, kaniko ]
+  merge-images:
+    needs: [ check-image, build-image ]
     runs-on: ubuntu-latest
-    outputs:
-      full-image: ${{ steps.manifest.outputs.image }}
 
     env:
       IMAGE_TAG: ${{ needs.check-image.outputs.tag }}
@@ -123,15 +117,9 @@ jobs:
 
       - name: Create multi-arch image
         run: |
-          docker manifest create neondatabase/build-tools:${IMAGE_TAG} \
-                         --amend neondatabase/build-tools:${IMAGE_TAG}-x64 \
-                         --amend neondatabase/build-tools:${IMAGE_TAG}-arm64
-
-      - name: Push image
-        id: manifest
-        run: |
-          digest=$(docker manifest push neondatabase/build-tools:${IMAGE_TAG})
-          echo "image=neondatabase/build-tools:${IMAGE_TAG}@${digest}" | tee -a $GITHUB_OUTPUT
+          docker buildx imagetools create -t neondatabase/build-tools:${IMAGE_TAG} \
+                                             neondatabase/build-tools:${IMAGE_TAG}-x64 \
+                                             neondatabase/build-tools:${IMAGE_TAG}-arm64
 
       - uses: docker/login-action@v3
         if: github.ref_name == 'main'
@@ -140,18 +128,11 @@ jobs:
           username: ${{ secrets.AWS_ACCESS_KEY_DEV }}
           password: ${{ secrets.AWS_SECRET_KEY_DEV }}
 
-      - uses: actions/setup-go@v5
-        if: github.ref_name == 'main'
-        with:
-          go-version: '1.22'
-
-      - name: Install crane
-        if: github.ref_name == 'main'
-        run: |
-          go install github.com/google/go-containerregistry/cmd/crane@8dadbe76ff8c20d0e509406f04b7eade43baa6c1 # v0.19.0
-
       - name: Promote image
         if: github.ref_name == 'main'
         run: |
-          crane copy neondatabase/build-tools:${IMAGE_TAG} pinned
-          crane copy neondatabase/build-tools:pinned 369495373322.dkr.ecr.eu-central-1.amazonaws.com/build-tools:pinned
+          docker tag neondatabase/build-tools:${IMAGE_TAG} neondatabase/build-tools:pinned
+          docker push neondatabase/build-tools:pinned
+
+          docker tag neondatabase/build-tools:pinned 369495373322.dkr.ecr.eu-central-1.amazonaws.com/build-tools:pinned
+          docker push 369495373322.dkr.ecr.eu-central-1.amazonaws.com/build-tools:pinned
