Deploy storage into new account

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -738,6 +738,55 @@ jobs:
           ansible-playbook deploy.yaml -i ${{ matrix.env_name }}.hosts.yaml
           rm -f neon_install.tar.gz .neon_current_version
 
+  deploy-new:
+    runs-on: [ self-hosted, Linux, k8s-runner ]
+    #container: 369495373322.dkr.ecr.eu-central-1.amazonaws.com/base:latest
+    # We need both storage **and** compute images for deploy, because control plane picks the compute version based on the storage version.
+    # If it notices a fresh storage it may bump the compute version. And if compute image failed to build it may break things badly
+    needs: [ push-docker-hub, calculate-deploy-targets, tag, regress-tests ]
+#    if: |
+#      (github.ref_name == 'main' || github.ref_name == 'release') &&
+#      github.event_name != 'workflow_dispatch'
+    defaults:
+      run:
+        shell: bash
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEV }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          submodules: true
+          fetch-depth: 0
+
+      - name: Setup python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Setup ansible
+        run: |
+          export PATH="/root/.local/bin:$PATH"
+          pip install --progress-bar off --user ansible boto3
+
+      - name: Redeploy
+        run: |
+          export DOCKER_TAG=${{needs.tag.outputs.build-tag}}
+          cd "$(pwd)/.github/ansible"
+
+          #if [[ "$GITHUB_REF_NAME" == "main" ]]; then
+            ./get_binaries.sh
+          #elif [[ "$GITHUB_REF_NAME" == "release" ]]; then
+          #  RELEASE=true ./get_binaries.sh
+          #else
+          #  echo "GITHUB_REF_NAME (value '$GITHUB_REF_NAME') is not set to either 'main' or 'release'"
+          #  exit 1
+          #fi
+
+          ansible-playbook deploy.yaml -i staging.test-us-east-2.hosts -e @ssm_config
+          rm -f neon_install.tar.gz .neon_current_version
+
   deploy-proxy:
     runs-on: dev
     container: 369495373322.dkr.ecr.eu-central-1.amazonaws.com/base:latest
