refactored to for loop

diff --git a/.github/workflows/trigger-e2e-tests.yml b/.github/workflows/trigger-e2e-tests.yml
--- a/.github/workflows/trigger-e2e-tests.yml
+++ b/.github/workflows/trigger-e2e-tests.yml
@@ -70,61 +70,14 @@ jobs:
       - name: check if ecr image are present
         id: check-ecr-image-present
         run: |
-          REPO=neon
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=compute-tools
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=compute-node-v14
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=vm-compute-node-v14
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=compute-node-v15
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=vm-compute-node-v15
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=compute-node-v16
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-          
-          REPO=vm-compute-node-v16
-          OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --region eu-central-1 --query "imageDetails[?imageTags[?contains(@, '${TAG}')]]" --output text)
-          if [ "$OUTPUT" == "" ]; then
-            echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
-            exit 1
-          fi
+          for REPO in neon compute-tools compute-node-v14 vm-compute-node-v14 compute-node-v15 vm-compute-node-v15 compute-node-v16 vm-compute-node-v16
+          do
+            OUTPUT=$(aws ecr describe-images --repository-name ${REPO} --image-ids imageTag=${TAG} --region eu-central-1 --output text)
+            if [ "$OUTPUT" == "" ]; then
+              echo "$Repo with image tag $TAG not found" >> $GITHUB_OUTPUT
+              exit 1
+            fi
+          done
 
       - name: Set PR's status to pending and request a remote CI test
         run: |
